travis:
  secure:
    BINSTAR_TOKEN: cCj2K4YURn9gRmCVU/FL32tVw4lCAkO6cdcimaH0EEY0g4InqI/WD8wcQeZx2bNME903203Jl/VY8LwS1/pS8JrYE+3BmUi8uBh1FCDjDd1QHsBY57kbFGEuHMlXXIK9JI4zLoTB6Wa1QsiXL/Z7yc8kDEzD2ljf2b88RFrdtMqjofgKPCONNYcapJau6ty0y7f8b70E/T7uIm43av54lvgSUr9LQMEaJ0pNEJNIyrzjqZhBbotubcSZB/uIqcNFkHORlJWOxirs9sdYeFvSxvZliiFqnVYdRv4SCl7/XUTJ790OvrSfJmiKA7eESxa/ZhM1U2wiAZrII3mBUy4ZVIssqWODdplFdinAND9BLUIbHyermzLuUumy6b5AkG6sf1fw5AFYv3E0ukeW0SdFSsqpLDtYx7T33oZGrPW+AqIje2uskhM4UM8WCh1m2TGje1m8zlLUyhvZ7D4YoULBNdCGvCmKXy1+4KEyJXI9sSMCpSCR1PlpIyjSBvyL4S4OBtFCKqhSsY7ild6CQYvKllH82xMRDJhWd83GgGy3Sdz6fARLq52g/wi5OKXSwpqwnpV9EQkr7o7ZA5IBp9qAxvlwJLWU+x4K4uMYWaz4aw/pp6x9Yy45YFZe/coJ/teQIGMnICNzMAjkIWid8Q6rIh1dyKwym2mbQ4mBn75FAEI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
