travis:
  secure:
    BINSTAR_TOKEN: MQLJ2oMrupO+sXUetBKSOlx9tM7aKHszXmFAxBRKquzJ3PhNj9Qff7YQQxAHvdUFMf2czp1wpU4BhGXkEU98XM9EFSyM1YieGCggfPERwYd1YCt7HS5mUBjnUkOskXQsv1JBjILoIw2xBY2yDA9pHGj9m+3p1I4kgI/cDudo1/NQQ+QLoAG4QoPy9YR8ERFG2Ru6mdTcpfm41zqtfsprh1u+gt4iUSej0EkOdgr86Pa7+KPEOtCJgJ9zmMlhuwUD0y+uM+bkZT8Bdlzk0ML/j0AJmdn1UDiBVRvC1j2qyZh8gsturhQExAtAd4+xOk0hYq/zeUW/7ar78yj4zQXjFQ5hc8CUbJM+2hvbQK4rhmzu/K1gCP2BA8athB05XWAtG8lNCFfuuA67IKpSrrMrhrKkXk0yw9hN69aD3Aym7LODmODp7ltHx4ukr6IS9qOpbomIoXmV9MMhJXdfE+ZcE0EtlpW6IuwotrJ7dp0CtaiDRDypLsXBUE873SzHawpTJrqBI/fOaNjJam3Dstf3V+ZBTb+EFd702UCPpMw21b+Awsx6dzcMECFpS4x7cd9UXNtcOeF9aN7jQHHMyVYOYdEbAnVN3l3h3AG3aENccfMcscPY5Onm2h5JI+bD3tS8qGXypBf1DQpXp3c10hQ16buDcWuijUKgN1DHBpBo5kM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
