travis:
  secure:
    BINSTAR_TOKEN: SWyQmJxMEblPPTnRHE4B+n8tf9tXx727pzejTcl5EdxIQqqQ6TQYruBVIuFhIQ+6KhFp8b4u1K0n/YyoIFRCnf0yE/LUXc8EEuKtyxYXcbRRlThkcbCmvYrPg5OKnK0covqnzUb2IB4BfaMS/eK2x9vicZnDvCSYqHTjQfNow+/+lDAL3XKsp2+4MVChzt1LOXk0PvpJ6TblBzQmRQRlyjVlw4KYqC4k3v1CspTdq+pNNvltPRqzsDKaSEweC8u6NhESuCl9fhH47sJDkZDfJdkyAaBZRBJetjIToG4HOyJlr0goh4gs/CtfYjURv3ntxA20Rcm4SuMwxpx1Xl7A1+VT4vggjKc5fHFUJkKCbzKBNBSkNERdXMyClrFthamOxbpdvj7yGDqDqOH4DZAaruAgYiYVpfBjmNO4dcX4sxdtuTan8OVpQwlkUQMnxqWKx9EbnWSKHl4j40b95DfrVAa/PUxJnSCx4HGYd20oLcIXzDpU1keaaB/XOUZ8DLJHdxPv+MB0chng1tcgk4kU0SgecKUZqHtvvTzuj/cVJfr4xWPjujpzMiecrwGO7P1ZHtWCoz99QhBybVdbOAkChZvbpjZpfNZxYn/xr9nCDbQ/bQiAkxEAVemYHq1ntvj/5/i/xAuEtISOY7fkfOopNlR+8qnyMZ2VnE+AnbNy/R0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
